#!/bin/bash

if ! dpkg -l packages-microsoft-prod.deb
then
  sudo wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  sudo dpkg -i packages-microsoft-prod.deb
  sudo rm packages-microsoft-prod.deb
fi

sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-6.0